[0m22:26:54.738247 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10e491310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10e471e90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10e472390>]}


============================== 22:26:54.744738 | 911d995d-41be-4737-a152-15cc53a8841f ==============================
[0m22:26:54.744738 [info ] [MainThread]: Running with dbt=1.6.1
[0m22:26:54.745506 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/Users/byronkim/.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m22:26:54.746230 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse dict {'dir': PosixPath('/Users/byronkim/.dbt')}
[0m22:26:54.746674 [info ] [MainThread]: Creating dbt configuration folder at 
[0m22:27:39.853290 [debug] [MainThread]: Starter project path: /usr/local/lib/python3.11/site-packages/dbt/include/starter_project
[0m22:27:39.874811 [info ] [MainThread]: 
Your new dbt project "dbtproject" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m22:27:39.875919 [info ] [MainThread]: Setting up your profile.
[0m22:27:49.746162 [info ] [MainThread]: No sample profile found for duckdb.
[0m22:27:49.747798 [debug] [MainThread]: Command `dbt init` succeeded at 22:27:49.747539 after 55.05 seconds
[0m22:27:49.748450 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109e17650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109d790d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10e49b6d0>]}
[0m22:27:49.748958 [debug] [MainThread]: Flushing usage events
[0m20:08:14.266820 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10a70c410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10a04a150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10a71b010>]}


============================== 20:08:14.283638 | 0285cb7b-c2a8-405b-aba1-e942b7eeeecc ==============================
[0m20:08:14.283638 [info ] [MainThread]: Running with dbt=1.6.1
[0m20:08:14.284707 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/byronkim/.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt snapshot', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m20:08:14.285588 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/byronkim/Documents/projects/data-etl-demo/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m20:08:14.286729 [debug] [MainThread]: Command `dbt snapshot` failed at 20:08:14.286522 after 0.05 seconds
[0m20:08:14.287306 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10a71a590>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10a71a710>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10611e050>]}
[0m20:08:14.287906 [debug] [MainThread]: Flushing usage events
[0m21:36:43.629345 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10ccd3710>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10cceaad0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10cceb210>]}


============================== 21:36:43.646130 | 2efac1b6-c243-4a2c-9057-b501be8650b4 ==============================
[0m21:36:43.646130 [info ] [MainThread]: Running with dbt=1.6.1
[0m21:36:43.647911 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/byronkim/.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt snapshot', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m21:36:43.648940 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/byronkim/Documents/projects/data-etl-demo/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m21:36:43.650104 [debug] [MainThread]: Command `dbt snapshot` failed at 21:36:43.649891 after 0.06 seconds
[0m21:36:43.650696 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10ccf3950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10ccf2ad0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10863fad0>]}
[0m21:36:43.651295 [debug] [MainThread]: Flushing usage events
[0m23:00:07.910086 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1103c1890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1103cee50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1103cf590>]}


============================== 23:00:07.931705 | e9e80a36-8932-4856-96c0-36850edeac65 ==============================
[0m23:00:07.931705 [info ] [MainThread]: Running with dbt=1.6.1
[0m23:00:07.932704 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/byronkim/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt docs generate', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m23:00:07.933462 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/byronkim/Documents/projects/data-etl-demo/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m23:00:07.934489 [debug] [MainThread]: Command `dbt docs generate` failed at 23:00:07.934313 after 0.05 seconds
[0m23:00:07.934970 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1103ce610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1103c1890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1103bbfd0>]}
[0m23:00:07.935474 [debug] [MainThread]: Flushing usage events
